---
- hosts: all
  gather_facts: true
  vars:
    - proxy_list: [google.com, localhost, yahoo.com, bing.com]
  tasks:
    - name: elect least latency proxy
      shell: "ping -c3 {{ item }} | tail -n1 | awk '{print $4}'| cut -d '/' -f2"
      with_items: "{{ proxy_list }}"
      register: pingout
    
    - debug:
        msg: "{{ pingout.results }}"

    - debug: msg="item.item={{item.item}}, item.stdout={{item.stdout}} type={{item.stdout|float|type_debug}}"
      with_items: "{{ pingout.results }}"

    - name: Populate proxy list
      set_fact:
        lproxies: "{{ lproxies | default([])}} + {{ [ {'name': item.item, 'latency': item.stdout|float} ] }}"
      with_items: "{{ pingout.results }}"
    
    - debug:
        msg: "elected_proxy: {{ (lproxies | sort(attribute='latency') | first).name }}"

