---
- hosts: all
  gather_facts: true
  vars:
    - proxy_list: [digitec.ch, yahoo.com, localhost, google.com, bing.com, telefonica.es]
  tasks:
    - name: template proxy-election script
      template:
        src: proxy-election.j2
        dest: /tmp/proxy-election
        mode: 0755

    - name: execute script
      shell: /tmp/proxy-election
      register: result

    - debug:
        msg: "elected_proxy: {{ result.stdout }}"

